apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-content
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cephfs-storage
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-db
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cephfs-storage
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-redis
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cephfs-storage
  resources:
    requests:
      storage: 1Gi
