apiVersion: v1
kind: Service
metadata:
  name: wordpress-lb
  namespace: wordpress
  annotations:
    metallb.io/loadBalancerIPs: 192.168.90.50
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
