apiVersion: v1
data:
  mariadb-password: TWFyaWFEYks4c0xhYjIwMjYh
  mariadb-root-password: Um9vdEs4c0xhYjIwMjYh
  wordpress-admin-password: V29yZFByZXNzSzhzTGFiMjAyNiE=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mariadb-password":"TWFyaWFEYks4c0xhYjIwMjYh","mariadb-root-password":"Um9vdEs4c0xhYjIwMjYh","wordpress-admin-password":"V29yZFByZXNzSzhzTGFiMjAyNiE="},"kind":"Secret","metadata":{"annotations":{},"name":"wordpress-secrets","namespace":"wordpress"}}
  creationTimestamp: "2026-08-25T23:16:46Z"
  name: wordpress-secrets
  namespace: wordpress
  resourceVersion: "41043"
  uid: 5c144dc4-b222-4437-9dcf-e8305f6b6501
type: Opaque
