apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"wordpress-content","namespace":"wordpress"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"5Gi"}},"storageClassName":"cephfs-storage"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rook-ceph.cephfs.csi.ceph.com
      volume.kubernetes.io/storage-provisioner: rook-ceph.cephfs.csi.ceph.com
    creationTimestamp: "2026-08-26T02:24:42Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: wordpress-content
    namespace: wordpress
    resourceVersion: "69827"
    uid: e7725828-d625-48e7-91c7-22a902b4e989
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 5Gi
    storageClassName: cephfs-storage
    volumeMode: Filesystem
    volumeName: pvc-e7725828-d625-48e7-91c7-22a902b4e989
  status:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 5Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"wordpress-db","namespace":"wordpress"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"5Gi"}},"storageClassName":"cephfs-storage"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rook-ceph.cephfs.csi.ceph.com
      volume.kubernetes.io/storage-provisioner: rook-ceph.cephfs.csi.ceph.com
    creationTimestamp: "2026-08-26T02:24:42Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: wordpress-db
    namespace: wordpress
    resourceVersion: "69831"
    uid: 8abfd554-9af3-472b-a0b8-8eb0160f1bb2
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: cephfs-storage
    volumeMode: Filesystem
    volumeName: pvc-8abfd554-9af3-472b-a0b8-8eb0160f1bb2
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"wordpress-redis","namespace":"wordpress"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":"cephfs-storage"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rook-ceph.cephfs.csi.ceph.com
      volume.kubernetes.io/storage-provisioner: rook-ceph.cephfs.csi.ceph.com
    creationTimestamp: "2026-08-26T02:24:42Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: wordpress-redis
    namespace: wordpress
    resourceVersion: "69834"
    uid: 968e93e5-42df-4a3b-919e-fe37f7bbcbd5
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: cephfs-storage
    volumeMode: Filesystem
    volumeName: pvc-968e93e5-42df-4a3b-919e-fe37f7bbcbd5
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
